// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import SingleMediaHighlight from './SingleMediaHighlight';

export {
	Hero,
	SingleMediaHighlight,
};

export const components = {
	hero: Hero,
	single_media_highlight: SingleMediaHighlight,
};
